spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AjayPal28/Config-Server
          username: AjayPal28
          password: ################
          default-label: main

server:
  port: 8888
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
